DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS pets CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS chats CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS attendees CASCADE;
DROP TABLE IF EXISTS follows CASCADE;

CREATE TABLE users (
  user_ID SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  sub_ID VARCHAR(255) NOT NULL,
  registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE pets (
  pet_ID SERIAL PRIMARY KEY NOT NULL,
  user_ID INTEGER REFERENCES users(user_ID),
  species VARCHAR(255) NOT NULL,
  breed VARCHAR(255) NOT NULL,
  medical_conditions VARCHAR(255) NOT NULL,
  diet VARCHAR(255) NOT NULL,
  allergies VARCHAR(255) NOT NULL,
  routines VARCHAR(255) NOT NULL,
  registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE posts (
  post_ID SERIAL PRIMARY KEY NOT NULL,
  user_ID INTEGER REFERENCES users(user_ID),
  pet_ID INTEGER REFERENCES pets(pet_ID),
  imageURL VARCHAR(255) NOT NULL,
  style VARCHAR(255) NOT NULL,
  sub_ID VARCHAR(255) NOT NULL,
  registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE events (
  creator_ID INTEGER REFERENCES users(user_ID),
  title VARCHAR(255) NOT NULL,
  event_description VARCHAR(255) NOT NULL,
  event_location VARCHAR(255) NOT NULL,
  scheduled_date DATE 
);
CREATE TABLE chats (
  chat_ID SERIAL PRIMARY KEY NOT NULL,
  user1_ID INTEGER REFERENCES users(user_ID),
  user2_ID INTEGER REFERENCES users(user_ID)
);
